function q=my_fun_mm(p)

global Vs_mag Vs_ang  Vr_mag Vr_ang  ps_ pr_ qs_ qr_ q T2
global a_mag a_ang b_mag b_ang c_mag c_ang d_mag d_ang
global k_mag k_ang f_mag f_ang g_mag g_ang h_mag h_ang

T2=Vr_ang;
VE=p(1);
Te0=p(2);
Tb0=p(3);
VB=p(4);

q=zeros(4,1);
q(1)= a_mag*Vs_mag^2*cos(-a_ang) ...
     + b_mag*VE*Vs_mag*cos(Vs_ang-b_ang-Te0) ...
     + c_mag*Vr_mag*Vs_mag*cos(Vs_ang-T2-c_ang) ...
     + d_mag*VB*Vs_mag*cos(Vs_ang-Tb0-d_ang)-ps_;
 
 q(2)= a_mag*Vs_mag^2*sin(-a_ang) ...
     + b_mag*VE*Vs_mag*sin(Vs_ang-b_ang-Te0) ...
     + c_mag*Vr_mag*Vs_mag*sin(Vs_ang-T2-c_ang) ...
     + d_mag*VB*Vs_mag*sin(Vs_ang-Tb0-d_ang)-qs_;
 
 q(3)= k_mag*Vs_mag*Vr_mag*cos(T2-Vs_ang-k_ang) ...
      + f_mag*VE*Vr_mag*cos(T2-Te0-f_ang) ...
      + g_mag*Vr_mag^2*cos(-g_ang) ...
      + h_mag*VB *Vr_mag*cos(T2-Tb0-h_ang)-pr_;
  
 q(4)= k_mag*Vs_mag*Vr_mag*sin(T2-Vs_ang-k_ang) ...
      + f_mag*VE*Vr_mag*sin(T2-Te0-f_ang) ...
      + g_mag*Vr_mag^2*sin(-g_ang) ...
      + h_mag*VB *Vr_mag*sin(T2-Tb0-h_ang)-qr_;
 